### ISSUE TITLE
Memory Leak when calling current_zone()

### ISSUE THREAD

**Issue by satishbhat-umd** [HowardHinnant/date#650]
=================================================================
==32643==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x568e50 in calloc (/build/sbhat/Laser/BT.BelvedereExchange/Tests/BT.BelvedereExchange.Tests+0x568e50)
    #1 0x7fffe1767163  (/lib64/libnsspem.so+0x15163)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x568e50 in calloc (/build/sbhat/Laser/BT.BelvedereExchange/Tests/BT.BelvedereExchange.Tests+0x568e50)
    #1 0x7fffe8ef4773  (/lib64/libnss3.so+0x75773)

Getting the following output when compiling using -fsanitize=address when the date::current_zone() fn is called

**Comment by HowardHinnant** [comment]
What OS/platform?

**Comment by satishbhat-umd** [comment]
CentOS 7.3

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by HowardHinnant** [comment]
Is it reproduceable in a small test such as:
```c++
#include "date/tz.h"

int
main()
{
    auto tz = date::current_zone();
}
```
And what build settings are you using (e.g. `USE_OS_TZDB`)?

**Comment by HowardHinnant** [comment]
Does it reproduce with this program?
```c++
#include "date/tz.h"

int
main()
{
    auto tz = date::locate_zone("Europe/Berlin");
}
```

**Comment by satishbhat-umd** [comment]
Reproduces in both cases and USE_OS_TZDB was not set when compiling the library (i.e. it will use a curl request to fetch the tzdb)

**Comment by HowardHinnant** [comment]
I'm not currently able to reproduce this on my platform.  Can you use this tool to locate the source line in tz.cpp where the leaked memory is allocated?

**Comment by satishbhat-umd** [comment]
It appears to be allocated in the curl_init function. I see the curl_deleter struct is passed to the destructor of the CURL object, but it seems to only call curl_easy_cleanup(...) in operator(). If I add a call to ::curl_global_cleanup() after that and recompile the library, I am able to call current_zone() without any memory leaks.

**Comment by HowardHinnant** [comment]
Really nice detective work.  I would not have found this.

Would you like for me to just fix it, or would you like to submit a P/R?

**Comment by satishbhat-umd** [comment]
Created a P/R here - https://github.com/HowardHinnant/date/pull/652

**Comment by HowardHinnant** [comment]
Fixed by #652
